/* eslint-disable global-require */
// Color codes for different themes
module.exports = {
	'Tomorrow Dark': require('./schemes/TomorrowDark'),
	'Tomorrow Light': require('./schemes/TomorrowLight'),
	'One Dark': require('./schemes/OneDark'),
	'One Light': require('./schemes/OneLight'),
	'Eighties Dark': require('./schemes/EightiesDark'),
	'Ocean Dark': require('./schemes/OceanDark'),
	'Ocean Light': require('./schemes/OceanLight'),
	'Solarized Dark': require('./schemes/SolarizedDark'),
	'Solarized Light': require('./schemes/SolarizedLight'),
	'Oceanic Next': require('./schemes/OceanicNext'),
	'Monokai Classic': require('./schemes/MonokaiClassis'),
	'Monokai Machine': require('./schemes/MonokaiMachine'),
	'Monokai Pro': require('./schemes/MonokaiPro'),
	'Monokai Octagon': require('./schemes/MonokaiOctagon'),
	'Monokai Ristretto': require('./schemes/MonokaiRistretto'),
	'Monokai Spectrum': require('./schemes/MonokaiSpectrum'),
	Material: require('./schemes/Material'),
	'Material Darker': require('./schemes/MaterialDarker'),
	'Material Palenight': require('./schemes/MaterialPalenight'),
	Zenburn: require('./schemes/Zenburn'),
	Nova: require('./schemes/Nova'),
	Nord: require('./schemes/Nord'),
	'Espresso Libre': require('./schemes/EspressoLibre'),
	'Espresso Soda': require('./schemes/EspressoSoda'),
	'Ayu Dark': require('./schemes/AyuDark'),
	'Ayu Light': require('./schemes/AyuLight'),
	'Ayu Mirage': require('./schemes/AyuMirage'),
};
